/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE DATABASE IF NOT EXISTS `IM`;
USE `IM`;
DROP TABLE IF EXISTS `chat_session`;

CREATE TABLE `chat_session` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `session_id` varchar(64) NOT NULL,
  `session_name` varchar(64) NOT NULL,
  `session_type` tinyint NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `session_id_i`
  ON `chat_session` (`session_id`);

