/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `TestTable`;

CREATE TABLE `TestTable` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_age` SMALLINT UNSIGNED NOT NULL,
  `name` TEXT NOT NULL,
  `update` TIMESTAMP NOT NULL,
  `math_score` DECIMAL NULL,
  `english_score` DECIMAL NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `name_i`
  ON `TestTable` (`name`);

CREATE INDEX `update_i`
  ON `TestTable` (`update`);

